/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lxl_login_demo_JniApiCall */

#ifndef _Included_com_lxl_login_demo_JniApiCall
#define _Included_com_lxl_login_demo_JniApiCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lxl_login_demo_JniApiCall
 * Method:    NanoOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lxl_login_demo_JniApiCall_NanoOpen
  (JNIEnv *, jobject);

/*
 * Class:     com_lxl_login_demo_JniApiCall
 * Method:    NanoClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lxl_login_demo_JniApiCall_NanoClose
  (JNIEnv *, jobject);

/*
 * Class:     com_lxl_login_demo_JniApiCall
 * Method:    NanoLogin
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_lxl_login_demo_JniApiCall_NanoLogin
        (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_lxl_login_demo_JniApiCall
 * Method:    NanoRegister
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_lxl_login_demo_JniApiCall_NanoRegister
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_lxl_login_demo_JniApiCall
 * Method:    NanoProcData
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_lxl_login_demo_JniApiCall_NanoProcData
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
